name: ecadev
recipe: drupal8
config:
  webroot: docroot
  php: '7.4'
  database: mysql:5.7
  myservice:
    type: mysql
    creds:
      user: mysql -> drupal8
      password: mysql -> drupal8
      database: database -> drupal8
  composer_version: 1-latest
  via: apache
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  drupal:
    cmd: "/app/vendor/drupal/console/bin/drupal --root=/app/docroot"
