# lando rebuild -y
# lando composer install
# lando php artisan key:generate
# lando php artisan migrate
# lando php -i | grep upload_max_filesize
# lando ssh --service appserver --user root --command "cat /etc/passwd"
# lando conteiner location
# /path/to/my/app => /app
# $HOME => /user
name: ecadev
recipe: drupal8
config:
  webroot: docroot
  php: '7.4'
  database: mysql:5.7
  # database: mysql:8.0
  myservice:
    type: mysql
    creds:
      user: mysql -> drupal8
      password: mysql -> drupal8
      database: database -> drupal8
  composer_version: 1-latest
  via: apache
services:
  appserver:
    run_as_root:
      - ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - echo "America/Sao_Paulo" > /etc/timezone  
  node:
    type: node:12
    ssl: false
    build:
     - cd /app/docroot/themes/custom/eca && yarn
    globals:
      npm-cli: latest
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  drupal:
    cmd: "/app/vendor/drupal/console/bin/drupal --root=/app/docroot"

