name: ecadev
recipe: drupal8
config:
  webroot: docroot
  php: '7.4'
  database: mysql:5.7
  myservice:
    type: mysql
    creds:
      user: mysql -> drupal8
      password: mysql -> drupal8
      database: database -> drupal8
  composer_version: 1-latest
  via: apache
services:
  appserver:
    run_as_root:
      - ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - echo "America/Sao_Paulo" > /etc/timezone  
  node:
    type: node:12
    ssl: false
    build:
     - cd /app/docroot/themes/custom/eca && yarn
    globals:
      npm-cli: latest
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  drupal:
    cmd: "/app/vendor/drupal/console/bin/drupal --root=/app/docroot"

